In [1]:
import scanpy as sc
import anndata



import importlib

import pandas as pd
import numpy as np
#import scanpy as sc
#import scycle as cc
# import scvelo as sv
#import anndata
from sklearn.decomposition import PCA

import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors

In [2]:
adata = sc.read_h5ad("data/all_human_miRNA_rpmm_harmonized_meta_data.h5ad")

In [5]:
adata.obs

                Biotype  Tissue Organ_system Project Sex Species
5628-SL-3674     tissue   blood        blood    PPMI   m     hsa
SRR3624071    cell_line   colon        bowel     SRA   u     hsa
SRR14749901      tissue   liver        liver     SRA   u     hsa
ERR1039452       tissue   brain        brain     SRA   u     hsa
SRR9130037    cell_line    CFBE     bronchus     SRA   u     hsa
...                 ...     ...          ...     ...  ..     ...
SRR19052519      tissue    skin         skin     SRA   u     hsa
SRR15687456      tissue  plasma        blood     SRA   u     hsa
SRR4035207       tissue  kidney       kidney     SRA   m     hsa
SRR2487648       tissue   ccRCC       kidney     SRA   m     hsa
SRR5756044       tissue   blood        blood     SRA   m     hsa

[46997 rows x 6 columns]

In [6]:
adata.var_names

Index(['hsa-let-7a-2-3p', 'hsa-let-7a-3p', 'hsa-let-7a-5p', 'hsa-let-7b-3p',
       'hsa-let-7b-5p', 'hsa-let-7c-3p', 'hsa-let-7c-5p', 'hsa-let-7d-3p',
       'hsa-let-7d-5p', 'hsa-let-7e-3p',
       ...
       'hsa-miR-9901', 'hsa-miR-9902', 'hsa-miR-9903', 'hsa-miR-9983-3p',
       'hsa-miR-9985', 'hsa-miR-9986', 'hsa-miR-99a-3p', 'hsa-miR-99a-5p',
       'hsa-miR-99b-3p', 'hsa-miR-99b-5p'],
      dtype='object', length=2656)

In [25]:
adata.obs["Tissue"]

5628-SL-3674     blood
SRR3624071       colon
SRR14749901      liver
ERR1039452       brain
SRR9130037        CFBE
                 ...
SRR19052519       skin
SRR15687456     plasma
SRR4035207      kidney
SRR2487648       ccRCC
SRR5756044       blood
Name: Tissue, Length: 46997, dtype: category
Categories (224, object): ['16HBE', '143B', 'A549', 'A2780', ..., 'vein', 'ventricle', 'vestibulochlear_complex', 'white_matter']

In [24]:
adata.obs["Sex"].unique()

['m', 'u', 'f', 'pool']
Categories (4, object): ['f', 'm', 'pool', 'u']

In [10]:
mask = adata.obs["Tissue"] == 'limb_muscle'

In [27]:
mask = (adata.obs["Tissue"] == 'limb_muscle') & (adata.obs["Sex"] == 'f')

In [31]:
expression_data = adata[mask, adata.var_names == adata.var_names].X
expression_data_df_females = pd.DataFrame(expression_data)

In [32]:
expression_data_df_females.columns = adata.var_names

In [33]:
expression_data_df_females

,hsa-let-7a-2-3p,hsa-let-7a-3p,hsa-let-7a-5p,hsa-let-7b-3p,hsa-let-7b-5p,hsa-let-7c-3p,hsa-let-7c-5p,hsa-let-7d-3p,hsa-let-7d-5p,hsa-let-7e-3p,...,hsa-miR-9901,hsa-miR-9902,hsa-miR-9903,hsa-miR-9983-3p,hsa-miR-9985,hsa-miR-9986,hsa-miR-99a-3p,hsa-miR-99a-5p,hsa-miR-99b-3p,hsa-miR-99b-5p
0,0.204864,115.099701,36579.044757,8.740885,8544.044432,4.472875,5940.626446,19.120686,3552.930771,4.916748,...,0.239009,0.000000,0.136576,19.871856,179.632017,0.000000,113.187633,4264.254437,30.012648,466.305732
1,0.000000,80.758170,8254.477567,7.669770,1634.112251,2.255815,1734.721592,87.525615,886.084059,9.925585,...,0.000000,0.000000,1.353489,0.902326,3.609304,0.000000,11.279074,3006.549984,42.860481,1127.907407
2,0.067177,104.950229,16472.414136,6.771416,5315.386824,3.237919,1862.233421,27.797737,2635.397450,0.994216,...,0.147789,0.107483,0.537414,0.053741,43.302130,0.080612,95.270060,1259.268392,4.675501,72.859898
3,0.227753,82.492255,10517.830899,8.426873,2594.839219,2.323084,1797.611469,21.955421,1094.445843,3.051895,...,0.455507,0.045551,0.000000,3.871807,75.750757,0.000000,88.277190,1455.844825,12.845288,251.257472
4,0.703203,176.816560,42019.938418,20.705430,10627.667533,3.672284,6651.521751,34.378827,3921.295926,7.110167,...,0.000000,0.156267,0.000000,25.002784,113.528264,0.000000,132.592886,2275.097032,20.627296,375.198020

In [34]:
mask = (adata.obs["Tissue"] == 'limb_muscle') & (adata.obs["Sex"] == 'm')
expression_data = adata[mask, adata.var_names == adata.var_names].X
expression_data_df_males = pd.DataFrame(expression_data)
expression_data_df_males.columns = adata.var_names
expression_data_df_males

,hsa-let-7a-2-3p,hsa-let-7a-3p,hsa-let-7a-5p,hsa-let-7b-3p,hsa-let-7b-5p,hsa-let-7c-3p,hsa-let-7c-5p,hsa-let-7d-3p,hsa-let-7d-5p,hsa-let-7e-3p,...,hsa-miR-9901,hsa-miR-9902,hsa-miR-9903,hsa-miR-9983-3p,hsa-miR-9985,hsa-miR-9986,hsa-miR-99a-3p,hsa-miR-99a-5p,hsa-miR-99b-3p,hsa-miR-99b-5p
0,0.178246,105.954751,23447.116751,11.433233,7535.315513,2.189884,3389.329779,29.537974,2791.262188,1.553290,...,0.840304,0.712986,0.560203,0.076391,69.592486,0.000000,120.061680,1942.198207,8.301189,122.735376
1,0.000000,98.136625,4882.872989,10.653100,5053.682183,1.685617,1388.746173,15.912225,572.502974,1.078795,...,2.359864,0.000000,0.000000,39.106316,62.165557,0.000000,58.254925,1353.415640,10.585675,168.359431
2,0.527818,136.689265,24510.809484,14.437367,3817.364017,3.477387,3367.539130,48.372941,2920.850101,6.395909,...,0.279433,0.155241,0.062096,33.780334,155.706226,0.000000,93.454784,4018.648856,9.687008,618.757605
3,0.287788,122.804396,18575.740967,7.464493,6447.738910,2.500155,1879.055648,33.131556,3370.353380,1.061217,...,0.683496,0.107920,0.989270,0.179867,55.219260,0.017987,98.801105,1830.437518,5.162191,103.999270
4,0.062339,40.411390,13487.835236,24.312290,10585.072460,8.509302,5902.338340,8.758658,2242.123044,7.792401,...,0.748070,0.000000,0.124678,21.101821,148.429649,0.000000,95.534833,411.002384,35.190482,131.037011
5,0.000000,87.069154,22072.074228,7.472244,8823.435665,0.525392,2467.008000,24.810185,3127.951317,0.291885,...,0.058377,0.000000,0.525392,0.000000,32.924574,0.000000,68.476109,1320.018573,4.086383,48.861469

In [19]:
my_mirs = ['hsa-miR-106a-5p',
 'hsa-miR-135a-5p',
 'hsa-miR-145-5p',
 'hsa-miR-150-5p',
 'hsa-miR-17-5p',
 'hsa-miR-181a-5p',
 'hsa-miR-18a-5p',
 'hsa-miR-200b-3p',
 'hsa-miR-20a-5p',
 'hsa-miR-22-3p',
 'hsa-miR-375',
 'hsa-miR-449a',
 'hsa-miR-9-5p']

In [21]:
my_mirs_in_table = [mir for mir in my_mirs if mir in adata.var_names]
my_mirs_in_table

['hsa-miR-106a-5p',
 'hsa-miR-135a-5p',
 'hsa-miR-145-5p',
 'hsa-miR-150-5p',
 'hsa-miR-17-5p',
 'hsa-miR-181a-5p',
 'hsa-miR-18a-5p',
 'hsa-miR-200b-3p',
 'hsa-miR-20a-5p',
 'hsa-miR-22-3p',
 'hsa-miR-449a',
 'hsa-miR-9-5p']

In [23]:
expression_data_df[my_mirs_in_table]

,hsa-miR-106a-5p,hsa-miR-135a-5p,hsa-miR-145-5p,hsa-miR-150-5p,hsa-miR-17-5p,hsa-miR-181a-5p,hsa-miR-18a-5p,hsa-miR-200b-3p,hsa-miR-20a-5p,hsa-miR-22-3p,hsa-miR-449a,hsa-miR-9-5p
0,0.245545,0.000000,15.223780,0.000000,23.326759,252.174545,7.857435,0.245545,103.865465,384.768756,0.000000,0.491090
1,90.720827,827.601339,6906.869830,888.941182,728.259131,4465.363082,289.951547,13.008895,1137.339381,31915.873625,5.224045,341.486348
2,22.966681,0.000000,4.189867,0.000000,778.849798,756.038297,90.159739,0.000000,457.316269,4497.745075,0.000000,0.155180
3,6.638706,6.213148,257.037093,100.601935,46.173054,413.748863,1.404342,2.000123,186.522115,10127.389115,0.042556,11.575180
4,0.958018,0.000000,5.748106,0.000000,53.648994,192.082558,3.832071,0.000000,43.589807,686.898724,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
93,0.109924,0.000000,5.386283,0.000000,1.099241,780.461380,0.000000,0.000000,2.308407,169.173248,0.000000,0.000000
94,5.055286,7.539721,206.143322,99.290998,37.201719,488.526402,0.432076,2.981322,152.047443,9939.556065,0.043208,6.970821
95,8.307038,3.845851,144.911662,53.534245,79.993699,770.093187,2.153677,1.538340,203.060928,13402.636592,0.000000,3.692017
96,1.668482,0.000000,16.684822,0.000000,14.807779,178.214753,7.925290,0.000000,53.599990,294.069985,0.417121,1.668482
97,12.075437,0.000000,110.969098,0.000000,685.176923,719.321261,66.206704,0.624592,377.253292,3194.161152,0.624592,0.208197

In [39]:
expression_data_df_females[my_mirs_in_table].to_csv('tissue_limb_muscle_females.csv', index=False)

In [40]:
expression_data_df_males[my_mirs_in_table].to_csv('tissue_limb_muscle_males.csv', index=False)